### ISSUE TITLE
question for evaluation metric.

### ISSUE THREAD

**Issue by Seoung-wook** [KimRass/text_spotting#1]
metric에 대해 살펴보았는데, 내용 이해는 되는데, 근거가 사용하시는 참고문헌이 있다면 알려주실 수 있나요?

**Comment by KimRass** [comment]
안녕하세요.

어떤 논문 등의 자료를 보고 구현한 metric은 아닙니다.

그저 IoU를 통해 f1 score를 계산하는 데 있어서 CER을 통해 일종의 부분점수의 개념을 도입하면 좀 더 정밀한 metric이 되겠다 생각하여 제 나름대로 구현한 것입니다.

관심 가지고 둘러봐 주셔서 감사합니다.

**Comment by Seoung-wook** [comment]
답변 감사합니다. ^^
CDAR2019 Robust Reading Challenge on Multi-lingual Scene Text Detection and
Recognition – RRC-MLT-2019에서 IoU 활용한 End-to-End Metric이 있는거 같더라고요.

https://arxiv.org/pdf/1907.00945.pdf
[image: image.png]

2023년 10월 11일 (수) 오후 3:39, Jongbeom Kim ***@***.***>님이 작성:

**Comment by KimRass** [comment]
정보 감사 드립니다. 참고하겠습니다.

다른 부분에 있어서도 궁금증 있으시면 서로 교류하면 좋겠네요.
