### ISSUE TITLE
AssertionError: datasets should not be an empty iterable 이슈

### ISSUE THREAD

**Issue by ghdwldn11** [KimRass/text_spotting#2]
동일한 데이터 셋을 사용하여 현재 학습을 진행 중에 있습니다.  

![image](https://github.com/user-attachments/assets/13caaaa6-5e42-4cc2-b192-aa9e30b1795a)

이러한 오류에 직면해 있는데 무엇이 문제일까요? 

경로에는 가이드와 같이 이미지와 csv파일을 똑같은 구조로 넣었습니다.

**Comment by KimRass** [comment]
안녕하세요.

오래 전 진행했던 프로젝트라 모든 코드에 대한 기억이 뚜렷하지 않습니다.

다만 지정된 경로에서 데이터를 찾을 수 없다는 뜻이므로 경로를 변경해보시기 바랍니다.
