### ISSUE TITLE
Usecols do not match columns, columns expected but not found: ['filename']

### ISSUE THREAD

**Issue by ghdwldn11** [KimRass/text_spotting#3]
[labels.csv](https://github.com/user-attachments/files/17359343/labels.csv)

readme 가이드처럼 해당 csv파일을 만들어서 진행 중이나 filename을 찾지 못하는 오류가 발생하고 있습니다. 

혹시 원인을 알 수 있을까요??

**Comment by KimRass** [comment]
`OCRDataset`의 `root`가 어떤 값을 가지는지 확인해 보시기 바랍니다.

`root`/`filename`으로 이미지의 경로가 결정됩니다.

**Comment by ghdwldn11** [comment]
어디를 봐야할지 모르겠습니다.
죄송하지만 조금만 더 자세히 알려주실 수 있으실까요??

**Comment by KimRass** [comment]
죄송합니다. 제목에 에러 내용을 적어주셨었는데 인지하지 못 했네요.

```python
self.df = pd.read_csv(
    os.path.join(
        os.path.dirname(root), 'labels.csv'
    ),
    sep='^([^,]+),',
    engine='python',
    usecols=['filename', 'words'],
    keep_default_na=False
)
```

여기서 `usecols`를 사용하고 있는데, 'labels.csv'에서 `filename`이라는 컬럼이름을 찾을 수 없다는 뜻으로 보입니다.

올려주신 'labels.csv'는 정상적으로 읽히는 것이 확인됐는데, 왜 저런 에러가 발생하는지 정확히는 모르겠네요.

**Comment by ghdwldn11** [comment]
넵 ㅠㅠ.. 정확한 해결방법이 안나와서 처음부터 다시 하고 있습니다!
현재 readme.ad에 Training set&Validation set을 보면서 적용 중입니다

이미지와 라벨은 unzipped 항목과 동일한 구조로 만들어 놨고, 여기에 "python3 prepare_dataset.py --dataset="/mnt/boryu/train_data_set/unzipped" --training" 경로를 잡고 training 옵션을 주면 "ValueError: too many values to unpack (expected 2)" 라는 오류를 발생시키는데 혹시 무엇을 설정하면 될까요?

정확한 오류는 아래처럼 발생합니다.
(myenv) root@82e2ed1e3e7b:/mnt/boryu/train_easyocr-main# python3 prepare_dataset.py --dataset="/mnt/boryu/train_data_set/unzipped" --training
Generating image patches for training...
  0%|                                                                                                                                                                            | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/boryu/train_easyocr-main/prepare_dataset.py", line 190, in <module>
    save_image_patches(
  File "/mnt/boryu/train_easyocr-main/prepare_dataset.py", line 120, in save_image_patches
    gt_bboxes, gt_texts = parse_json_file(json_path, load_image=False)
    ^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

**Comment by KimRass** [comment]
`parse_json_file()` 함수가 잘못 설계되어 있는 것 같습니다.

즉시 수정하겠습니다. 잠시만요.

**Comment by KimRass** [comment]
'prepare_dataset.py'의 수정사항을 반영한 다음 다시 해보시겠어요?

**Comment by ghdwldn11** [comment]
감사합니다 해결되었습니다!
