### ISSUE TITLE
학습 진행 중 오류

### ISSUE THREAD

**Issue by JW-HONG831** [KimRass/text_spotting#4]
![학습오류](https://github.com/user-attachments/assets/0a5b9db9-aec7-4e71-b05a-d10525cc446c)

iter_50000.pth 파일을 연달아 학습을 진행 중에 있어 위의 사진과 같은 오류가 발생하였습니다.
혹시 어디를 수정하면 될지 알려주시면 감사하겠습니다.

**Comment by KimRass** [comment]
음.. 저 에러가 발생했을 때 `labels`를 프린트해보시겠어요?

**Comment by JW-HONG831** [comment]
답변이 늦어서 죄송합니다.
config.yaml 파일에서 show_number 값을 조절해서 학습시키니 정상적으로 동작하였습니다
